apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: volcano-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-volcano-dev
product: kind
registry: volcano-registry
kindV1Alpha4Cluster:
  name: kind-volcano-dev
  nodes:
    - role: control-plane
    - role: worker
    - role: worker
    - role: worker
    - role: worker
